const images = {
  splash_bg: { uri: 'splash_bg' },
  splash_logo: { uri: 'splash_logo' },
  ic_up_arrow: { uri: 'ic_up_arrow' },
  ic_down_arrow: { uri: 'ic_down_arrow' },

  ic_chart_bar: { uri: 'ic_chart_bar' },
  ic_file_alt: { uri: 'ic_file_alt' },
  ic_file_invoice: { uri: 'ic_file_invoice' },
  ic_plus: { uri: 'ic_plus' },
  minus_square: { uri: 'minus_square' },
  exchange_alt: { uri: 'exchange_alt' },
  transform: { uri: 'transform' },
  product_id: { uri: 'product_id' },
  product_originality: { uri: 'product_originality' },
  warranty_inquiry: { uri: 'warranty_inquiry' },
  flash_light: { uri: 'flashlight' },
  message_icon: { uri: 'message' },
  docsetting_icon: { uri: 'docsetting' },
  dots_icon: { uri: 'dots' },
  boxes: { uri: 'boxes' },
  close: { uri: 'close' },
  truck: { uri: 'truck' },
  announcemet: { uri: 'announcemet' },
  document: { uri: 'document' },
  news: { uri: 'news' },
  straightline: { uri: 'straightline' },
  newssectionicon: { uri: 'newssectionicon' },
  inquiryofbusinessrules: { uri: 'inquiryofbusinessrules' },
  goods: { uri: 'goods' },
  person: { uri: 'person' },
  salewithdraft: { uri: 'salewithdraft' },
  mobile: { uri: 'mobile' },
  openedmessage: { uri: 'openedmessage' },
  house_stuff_retail: { uri: 'house_stuff_retail' },
  warehouse_docoment_managmnet: { uri: 'warehouse_docoment_managmnet' },
}
export default images
