const strings = {
  appName: 'سامانه جامع تجارت',
  ok: 'تایید',
  notOk: 'عدم تایید',
  askLater: 'بعدا بپرس',
  submit: 'ثبت',
  cancel: 'انصراف',
  delete: 'حذف',
  error: 'خطا',
  retry: 'تلاش مجدد',
  continue: 'ادامه',
  yes: 'بله',
  no: 'خیر',
  warning: 'اخطار',
  appVersion: 'نسخه برنامه: %1$',
  exit: 'خروج',
  exitApp: 'خروج از برنامه',
  exitAppQuestion: 'برای خروج از برنامه اطمینان دارید؟',
  next: 'بعدی',
  searchText: 'متن جستجو',
  guideScreenTitle: 'راهنمای سامانه تجارت',

  welcomeToSystem: 'به سامانه جامع تجارت خوش امدید',
  enterToSystem: 'ورود به سامانه جامع تجارت',
  nationalCode: 'کد ملی',
  enterActivateCode: 'کد تایید دریافتی را وارد کنید :',
  activateCodeWrongError: 'کد اشتباه است',
  enterNationalCode: 'کد ملی خود را وارد کنید ',
  changeNationalCode: 'تغییر کد ملی ',
  incorrectNationalCode: 'کد ملی وارد شده صحیح نمیباشد',
  resendActivateCode: 'ارسال مجدد کد ',
  separation: 'تفکیک / تبدیل',
  operationDoneSuccessfully: 'عملیات تفکیک، موفقیت آمیز بود',

  nationalCodeIsNotValid: 'کد ملی وارد شده ، نامعتبر است',
  activationCodeNotValidError: 'لطفا کد معتبری وارد نمایید',
  notSubmitedNationalCode: 'نقش تجارت داخلی یافت نشد',
  roleTitle: 'عنوان نقش :',
  person_company_Name: 'نام شخص / شرکت :',
  township: 'شهرستان :',
  haveLicences: 'دارای مجوز :',

  userAccess: 'انتخاب نقش کاربری',
  chooseyourAccess: 'نقش کاربری خود را انتخاب نمایید :',

  seeInventory: 'مشاهده موجودی ',
  store: 'انبار :',
  productCode: 'شناسه کالا : ',
  productSummery: 'شرح کالا : ',
  measuringUnit: 'واحد اندازه گیری : ',
  Inventory: 'موجودی :',

  showTrackingID: 'نمایش شناسه های رهگیری',
  dateOfDeclaration: 'تاریخ اظهار : ',
  serialNumber: 'شماره سریال : ',
  garanteNumber: 'شماره گارانتی : ',

  noStuffToShow: '" کاربر گرامی، شما موجودی برای نمایش ندارید "',
  temporaryStorageExtraText: ' (عدم ارسال به سامانه جامع انبار)',

  /***************** اخذ نقش تجارت داخلی ****************/
  createBussinesRole: 'اخذ نقش تاجر داخلی',
  nationalNumber: 'شناسه ملی',

  nameOfBussinesUnit: 'نام واحد تجاری',
  nameOfBussinesUnitError: 'نام واحد تجاری را وارد کنید',

  activityRegion: 'حوزه فعالیت ',
  activityRegionError: 'حوزه فعالیت را انتخاب نمایید ',

  activityType: 'نوع فعالیت',
  activityTypeError: 'نوع فعالیت را انتخاب نمایید ',

  activityLicense: 'مجوز فعالیتی ',

  licenseNumber: 'شماره مجوز ',
  licenseNumberError: 'شماره مجوز باید وارد شود',
  obligationToIranRules: 'متعهد به قانون تجارت کشور ج.ا.ا می باشم',
  registerInfos: 'ثبت اطلاعات',
  submitFinallInfos: 'ثبت نهایی اطلاعات',
  smsCodeError: 'کد دریافتی را وارد کنید',
  submitSuccesfully:
    'اخذ نقش تاجر داخلی با موفقیت انجام گردید، جهت انجام فعالیت در نقش اخذ شده از طریق کدملی وارد نرم افزار شوید.',
  /***************** استعلام شناسه کالا ****************/
  otherServices: 'سایر خدمات',
  StuffInquriy: 'استعلام شناسه کالا',
  guaranteeInguriy: 'استعلام گارانتی',
  stuffOriginInquriy: 'استعلام اصالت کالا',
  inquriy: 'استعلام',
  StuffInquriyError: 'کد کالای 13 رقمی را وارد کنید',
  stuffType: 'نوع کالا : ',
  goodsInquriy: 'استعلام شناسه کالا ',
  import: 'وارداتی',
  product: 'تولیدی',
  active: 'فعال',
  inActive: 'غیر فعال',
  stuffCodeDoesntExist: '" کالایی با شناسه ورودی، در سامانه وجود ندارد "',
  scanBarCode: 'جهت استعلام شناسه کالا، بارکد را اسکن کنید',

  /***************** استعلام گارانتی ****************/
  guranterCode: 'شناسه گارانتی:',
  guranteCompany: 'شرکت گارانتی کننده :',
  guranteTime: 'مدت گارانتی ( به ماه ) :',
  importet_exporter: 'واردکننده / تولیدکننده :',
  premissionToUseCamera: 'مجوز دسترسی به دوربین',
  premissionMessage: 'برای استفاده از بارکد خوان، مجوز دسترسی به دوربین را تایید کنید ',
  // notValidGurantecode:'کد گارانتی وارد شده ، معتبر نمیباشد',
  premissionNotGranted: 'مجوز دسترسی به دوربین تایید نشده است.\nدوباره سعی کنید',
  scanQuranteeCodeBarCode: 'جهت استعلام گارانتی کالا، بارکد را اسکن کنید',
  warrantyStartTime: 'تاریخ شروع گارانتی :',
  guranteHasNotStartedyet: 'گارانتی هنوز شروع نشده است',

  /***************** استعلام اصالت کالا  ****************/
  StuffOriginalInquriy: 'استعلام اصالت کالا',
  trackingCode: 'شناسه رهگیری : ',
  person_companyDeclarative: 'شخص/شرکت اظهار کننده :',
  code_NationalNumber: 'کد / شناسه ملی بهره بردار',
  enter15LengthCode: 'شناسه رهگیری 15 رقمی وارد کنید',
  scanOriginalCodeBarCode: 'جهت استعلام اصالت کالا، بارکد را اسکن کنید',

  /****************************** storeManagment Screen  ******************************/
  storeManagment: 'مدیریت انبارها',
  noStoreRegisterYet: 'هنوز انباری ثبت نشده است\nبا انتخاب دکمه " + " انبار جدید را اضافه کنید.',
  addNewStore: 'افزودن انبار جدید',
  postalCode: 'کد پستی : ',
  storeName: 'نام انبار :',
  OperationStatus: 'وضعیت بهره برداری:',
  submitStore: 'ثبت انبار',
  address: 'آدرس :',
  operator: 'بهره بردار :',
  enterTenNumberPostalCode: 'کد پستی 10 رقمی را وارد کنید',
  enterStoreName: 'نام انبار را وارد کنید',
  chooseOneOfTypes: 'یکی از گزینه ها را انتخاب کنید',
  storeRegisterSuccessfully: 'انبار جدید با موفقیت ثبت شد',
  storeDoesNotSubmitInStoreSystem:
    'خطا ! \n درصورتیکه بهره بردار انبار می باشید، جهت ثبت انبار به سامانه جامع انبار ها به آدرس www.nwms.ir مراجعه نمایید.',

  /****************************** ShippingDocumnent Screen  ******************************/
  shippingDocumentManagment: 'مدیریت اسناد حمل (بارنامه)',
  shippingDocument: 'اسناد حمل :',
  dateMustSelected: 'تاریخ باید انتخاب شود',
  billNum_Serial: 'شماره و سریال بارنامه :',
  shippingCompanyName: 'نام شرکت حمل و نقل :',
  startingCity: 'شهر مبدا :',
  destinationCity: 'شهر مقصد :',
  IntroductionSituation: 'آخرین وضعیت معرفی نامه :',
  ownerShipSituation: 'وضعیت تایید یا رد مالکیت :',
  introductionDetails: 'جزئیات معرفی نامه و بارنامه',
  confirmOwnerShip: 'تایید مالکیت',
  declineOwnerShip: 'رد مالکیت',
  shiipingDocumnetDetails: 'جزییات اسناد حمل (بارنامه)',
  introductionInfos: 'اطلاعات معرفی نامه و بارنامه',
  billInterceptionCode: 'کد رهگیری بارنامه :',
  senderInfos: 'اطلاعات فرستنده ',
  senderTitle: 'عنوان فرستنده :',
  senderCode_natinalCode: 'کد/شناسه ملی فرستنده :',
  startingPostalCode: 'کد پستی مبدا :',
  reciverInfos: 'اطلاعات گیرنده ',
  reciverTitle: 'عنوان گیرنده :',
  reciverCode_natinalCode: 'کد/شناسه ملی گیرنده :',
  destinationPostalCode: 'کد پستی مقصد :',
  driver_fleetInfos: 'اطلاعات راننده و ناوگان',
  name_lastName: 'نام و نام خانوادگی :',
  fleetNumberPlates_Serial: 'شماره پلاک و سریال ناوگان :',
  rejectByReciver: 'رد توسط گیرنده',
  confirmbyReciver: 'تایید توسط گیرنده',
  rejectBySender: 'رد توسط فرستنده',
  confirmByReciver: 'تایید توسط فرستنده',
  confirmOwnerShipPopUp: 'برای تایید مالکیت، اطمینان دارید؟',
  ignoreOwnerShipPopUp: 'برای رد مالکیت، اطمینان دارید؟',
  changeOwnerShipSuccesfully: 'تایید / رد مالکیت، موفقیت امیز بود',
  /****************************** Menu Screen  ******************************/
  docsManagement: 'مدیریت اسناد',
  incomingEntry: 'اظهار ورودی',
  seeInventory: 'مشاهده موجودی',
  transferOwnershipAndPlace: 'انتقال مالکیت و مکان',
  outgoingEntry: 'اظهار خروج',
  comingSoon: 'به زودی ...',
  userRoleCode: 'کد نقش :',
  incomingDocManagment: 'مدیریت اسناد ورودی',
  outgoingDocManagment: 'مدیریت اسناد خروجی',
  waitingToConfirm: 'در انتظار تایید  :',
  confirmed: 'تایید شده :',
  saleDocs: 'اسناد فروش',
  buyDocs: 'اسناد خرید',
  operation: 'عملیات',
  otherServices: 'سایر خدمات',
  messages: 'پیام ها',
  inquiryOfBusinessRules: 'استعلام ضوابط تجاری',
  declarationOfProductionOfGoods: 'اظهار تولید کالا',
  internationalBusinessDashboard: 'داشبورد تجاری',
  dontHaveAccess: 'شما به این قسمت دسترسی ندارید',
  saleWithDraftPaper: 'فروش با حواله\n تایر سنگین',
  homeApplianceRetail: 'خرده فروشی\nلوازم خانگی',
  wareHouseDocumentManagment: 'مدیریت اسناد انبار',

  /****************************** استعلام ضوابط تجاری  ******************************/
  tariffCode: 'کد تعرفه :',
  tariffCodeInformation: 'اطلاعات کد تعرفه',
  traiffSummery: 'شرح تعرفه :',
  stuffPriorty: 'اولویت کالایی :',
  inputSalary: 'حقوق ورودی :',
  permissions: 'مجوز ها',
  title: 'عنوان',
  value: 'مقدار',
  rules: 'ضابطه',
  businessRules: 'ضوابط تجاری',
  permission: 'مجوز',
  condition: 'شرط',

  /*********** ToolTip ************/
  viewInventory: 'در این بخش می توانید موجودی کالاهای خود را در هر انبار مشاهده نمایید.',
  viewInteryStuffDocumnets:
    'در این بخش می توانید اسناد ورودی به انبار خود را مشاهده نموده و اسناد خرید خود را تایید یا رد نمایید.',
  viewOutgoingStuffDocumnets: 'در این بخش می توانید اسناد خروج کالا از موجودی خود را مشاهده نموده و تعیین وضعیت نمایید.',

  viewTransferOwnersgip: 'در این بخش می توانید اسناد انتقال مالکیت (فروش) و انتقال مکان را ثبت نمایید.',
  viewStuffIntery:
    'در این بخش می توانید اسناد ورود کالا به انبار شامل موجودی اولیه، اظهار واردات، اظهار خرید و ... را ثبت نمایید.',
  viewStuffOutgoing: 'در این بخش می توانید اسناد خروج کالا از انبار شامل اسقاط، صادرات و ... را ثبت نمایید.',
  storeManagmentTooltip: 'در این قسمت میتوانید انبارهای خود را مدیریت کنید',
  storeDocumentManagmentTooltip: 'در این قسمت میتوانید اسناد انبار خود را مدیریت کنید',
  shippingDocManagmentTooltip:
    'در این بخش می توانید اسناد بارنامه خود را مشاهده نموده و نسبت به تایید یا رد مالکیت آنها اقدام نمایید',
  declarationOfProductionOfGoodsTooltip: 'در این بخش می توانید اسناد اظهار تولید و استعلام از سامانه بهین یاب را ثبت نمایید.',
  inquiryofbusinessrulesTooltip: 'در این بخش می توانید ضوابط تجاری را بر حسب تعرفه استعلام نمایید.',
  saleWithDraftTooltip: 'در این بخش می توانید نسبت به استعلام اطلاعات حواله و ثبت فروش اقدام نمایید.',
  /****************************** Drawer items *******************************/
  checkAppVersion: 'بررسی نسخه',
  changeRole: 'تغییر نقش',
  logout: 'خروج از حساب',
  viewStuffInventory: 'مشاهده موجودی کالا',
  incomingStuffEntry: 'اظهار ورود کالا',
  outgoingStuffEntry: 'اظهار خروج کالا',
  callSupportUnit: 'تماس با پشتیبانی',
  appGuide: 'راهنمای نرم افزار',

  /********************** CommercialDocInquiry Screen  ***********************/
  CommercialDocInquiry: 'استعلام اسناد تجاری  ',
  totalNumberOfDocs: 'تعداد کل اسناد :',
  docNumber: 'شماره سند : ',
  docDate: 'تاریخ سند :',
  docType: 'نوع سند :',
  nameOf_Seller_Buyer: 'خریدار / فروشنده : ',
  originStore: 'انبار مبدا :',
  destinationStore: 'انبار مقصد :',
  situation: 'وضعیت : ',
  details: 'جزییات',

  import_export: 'خروجی / ورودی :',
  docTypes: 'نوع اسناد :',
  fromDate: 'از تاریخ :',
  untilDate: 'تا تاریخ :',
  docSituation: 'وضعیت اسناد :',
  docInquiry: 'استعلام اسناد',

  price: 'مبلغ (ریال) :',
  commingSoon: 'این بخش به زودی راه اندازی خواهد شد.',

  dischargeConfirmation: 'تایید تخلیه',

  /********************** firstModal  Screen  ***********************/
  destinationInfo: 'اطلاعات مقصد',
  deliveryDate: 'تاریخ تحویل :',
  Transform_Store_Info: 'اطلاعات حمل و انبار',
  withoutBill: 'بدون بارنامه  ',
  billNumber: 'شماره بارنامه :',
  billSerial: 'سریال بارنامه :',
  billDate: 'تاریخ بارنامه :',
  selectWareHouseError: 'انبار را انتخاب کنید',
  enterBillNumberError: 'شماره بارنامه را وارد کنید',
  enterBillSerialError: 'سریال بارنامه را وارد کنید',

  /**********************  ***********************/

  changeDocStatusQuestion: 'برای تغییر وضعیت سند %1$ به "%2$"، مطمئن هستید؟',
  docStatusChangedSuccessfully: 'وضعیت سند %1$ به "%2$" تغییر یافت',

  choseTabs: 'لطفا همه گزینه ها را پر کنید',
  chooseUserRole: 'لطفا یکی از گزینه های نقش کاربری را انتخاب کنید',
  changeDocSituation: '',

  /****************************** IcomingEntery Screen  ******************************/

  text: 'متن جستجو :',
  search: 'جستجو',
  searchFilter: 'فیلتر جستجو',
  IcomingEnteryNumber: 'شماره اظهار :',
  date: 'تاریخ :',
  IcomingEnteryType: 'نوع اظهار :',
  summery: 'شرح :',
  finalSubmit: 'ثبت نهایی',
  continueSubmiting: ' ادامه ثبت',
  edit: 'ویرایش',
  cancelRequest: 'ابطال درخواست',
  PresentingInventory: 'اظهار ورود',

  /****************************** CommercialDocInquiry Screen  ******************************/
  IncomingProductInquiry: 'اظهار ورود کالا ',
  baseInfo: 'اطلاعات پایه',
  submitProduct: 'ثبت کالا',
  finilizeSubmit: 'نهایی سازی اظهار',
  docSummery: 'شرح سند :',
  sellerName: 'نام فروشنده :',
  code_natinaleNumber: 'کد ملی :',
  mobile: 'تلفن همراه :',
  submitOrderNumber: 'شماره سفارش :',
  currencyOriginNumber: 'شماره منشاء ارز :',
  cotajhNumber: 'شماره کوتاژ :',
  primarySubmit: 'ثبت اولیه',

  invoiceNumber: 'شماره صورتحساب :',
  sellTypeError: 'نوع سند را انتخاب کنید',
  sellerNameError: 'نام فروشنده را انتخاب کنید',
  notValidPersianCharacter: ' فقط حروف فارسی قابل قبول است',
  code_natinaleNumberError: 'کد ملی را وارد کنید ',
  nationalCodeOrNumberError: 'کد/شناسه ملی را وارد کنید ',
  mobileError: 'شماره تلفن همراه را وارد کنید',
  mobilePhoneNotCorrect: 'شماره وارده صحیح نمی باشد',
  submitOrderNumberError: 'شماره سفارش را وارد کنید ',
  currencyOriginNumberError: 'شماره منشاء ارز راوارد کنید',
  cotajhNumberError: 'شماره کوتاژ را وارد کنید',
  notValidNationalCode: 'کد ملی وارد شده صحیح نمیباشد',

  temporaryStorage: 'انبار موقت',
  productList: 'لیست کالا',
  productGroup: 'گروه کالا :',
  productCategory: 'طبقه کالا :',
  productId: 'شناسه کالا :',
  idType: 'نوع شناسه :',
  mesurementUnit: 'واحد اندازه گیری :',
  amount: 'تعداد :',
  subjectToInterception: 'مشمول رهگیری :',
  submitNewProduct: 'ثبت کالای جدید',
  amount_value: 'تعداد / مقدار :',
  amountError: 'مقدار را وارد کنید',
  productIdActionBar: 'شناسه کالا ',
  stuffAddsuccessfully: 'کالا با موفقیت اضافه شد',
  deleteStuffQuestion: 'آیا مطمئن هستید که میخواهید کالا با شناسه %1$ را حذف کنید؟',
  chooseLeastOneProduct: 'حداقل یک کالا انتخاب کنید',
  selectStuff_Group_Class: 'گروه کالا و طبقه کالا را انتخاب کنید',
  submit_next: 'ثبت و بعدی',
  submit_finish: 'ثبت و تمام',
  sameStuffCodeErrorMessage: 'این شناسه کالا برای اظهار قبلا درج شده است',
  deleteSelectedStuff: 'کالای انتخاب شده حذف شود ؟',
  stuffDeleteSuccessfully: 'کالا با موفقیت حذف شد',
  changedSuccessfully: 'ویرایش موفقیت آمیز بود',
  SameStuffCode: 'این شناسه کالا برای اظهار قبلا درج شده است',
  productListEmptyMessage: "هنوز کالایی ثبت نشده است\nبا انتخاب دکمه ' + ' کالای جدید اضافه کنید",
  docSubmitSuccessfully: 'سند با موفقیت ثبت شد',
  noStuffIsAvailable: 'کالایی برای سند وجود ندارد',
  stockProductPrimaryDeclareSuccessfully:
    'توجه!\nثبت سند با وضعیت ثبت اولیه انجام شد، جهت ثبت نهایی به صفحه مدیریت اسناد مراجعه نمایید.',
  place: 'مکان :',
  choseOneOfWareHouses: 'ابتدا مکان مورد نظر را انتخاب نمایید سپس اقدام به انتخاب شناسه کالایی نمایید',
  transferOwnership_Sale: 'انتقال مالکیت / فروش',
  transferPlace_shipment: 'انتقال مکان / حمل',
  primaryInfos: 'اطلاعات اولیه',
  transferPlace: 'انتقال مکان',
  stuffInfo: 'اطلاعات کالا',
  description: 'توضیحات :',
  buyerNationalNumber: 'کد/شناسه ملی خریدار :',
  buyerRole: 'نقش خریدار :',
  transferOwnership: 'انتقال مالکیت',
  buyerName: 'نام خریدار :',
  buyerMobileNum: 'تلفن همراه خریدار :',
  saleToBusinessman: 'فروش به تاجر',
  saleToConsumer: 'فروش به مصرف کننده',
  backFromSale: 'برگشت از خرید',
  saleToBusinessmanToolTip:
    'در صورتیکه قصد فروش کالا به فعال تجاری ( نظیر تولید کننده، عمده فروش و خرده فروش ) را دارید از این گزینه استفاده نمایید.',
  saleToConsumerToolTip: 'در صورتیکه قصد فروش به آخرین زنجیره تجاری یعنی مصرف کننده نهایی را دارید از این گزینه استفاده نمایید.',
  backFromSaleToolTip: 'در صورتیکه قصد بازگشت کالای خریداری شده به فروشنده را دارید از این گزینه استفاده نمایید.',
  backFromSaleToolTip: 'در صورتیکه قصد بازگشت کالای خریداری شده به فروشنده را دارید از این گزینه استفاده نمایید.',
  contractWorkDeliveryTooltip:
    'در صورتیکه قصد انتقال کالاهای تولید شده بصورت حق العمل کاری به مالک کالا را دارید از این گزینه استفاده نمایید.',
  chooseproductCategory: 'طبقه کالا را انتخاب کنید',
  chooseRightNumberLength: 'عددی بین 10 یا 11 رقم وارد کنید',
  unknoknWarehouse: 'انبار مقصد نامشخص',
  before: 'قبلی',
  valueUnit: 'مبلغ واحد(ریال) :',
  stuffSelection: 'انتخاب کالا',
  enterDestinationStorePostalCode: 'کد پستی انبار مقصد',
  DestinationStorePostalCodeError: 'کد پستی را وارد کنید',
  notCorrectAmount: 'تعداد صحیح نمیباشد',
  notCorrectUnitPrice: 'مبلغ صحیح نمی باشد',
  itemSelectedBefore: 'این کالا قبلا انتخاب شده است',
  chooseAtleastOneOfCheckBoxes: 'یکی از گزینه های انتقال مالکیت یا انتقال مکان را انتخاب کنید',
  buyerNameErrorText: 'نام خریدار را وارد کنید',
  chooseBuyerRole: 'نقش خریدار را انتخاب کنید',
  transferPlaceAndOwnershipInqueryMessage:
    'عملیات با موفقیت انجام خواهد شد. جهت ثبت سند فروش دکمه استعلام و ثبت را انتخاب نمایید',

  transferListEmptyMessage: "هنوز کالایی اضافه نشده است\nبا انتخاب دکمه ' + ' کالای جدید اضافه کنید",
  docNumberErorrText: 'شماره سند را وارد کنید',
  internationally: 'بین المللی',
  withBill: 'دارای بارنامه  ',
  billCreation: 'صدور بارنامه  ',
  withoutBillTooltip: 'در صورتیکه حمل کالا بدون بارنامه انجام شده است، از این گزینه استفاده نمایید.',
  withBillTooltip:
    'در صورتیکه برای حمل کالا قبلا بارنامه صادر شده است، از این گزینه استفاده نمایید و اطلاعات بارنامه را وارد نمایید.',
  billCreatinTooltip:
    'در صورتیکه هنوز بارنامه صادر نشده است از این گزینه استفاده نمایید و پس از صدور بارنامه در مدیریت اسناد ورودی، گزینه تایید تخلیه را انتخاب نمایید.',
  buyDocNumber: 'شماره سند خرید : ',
  buyDocNumberError: 'شماره سند خرید را وارد کنید',
  /***************************** اظهار خروج کالا  *********************/
  productTakeOut: 'اظهار خروج کالا',
  productDocNumber: 'شماره سند تولید:',
  productDocNumberError: 'شماره سند تولید را وارد کنید',
  productDocNumberToolTip: 'شماره سند تولید یا دریافت حق العمل کاری را ثبت نمایید.',
  cortajToolTip: 'شماره کوتاژ و کد  گمرگ را با علامت - جدا کنید\n مثال: 1552614 - 35306',
  productionDecline: 'جهت ثبت کاهش موجودی تا حداکثر ۵٪ از محصول تولید شده، شماره سند تولید را ثبت نمایید',
  /***************************** اظهار تولید کالا  *********************/

  productionDeclaration: 'اظهار تولید کالا',
  newProductionDeclaration: 'اظهار تولید جدید',
  inquiryFromBahinyab: 'استعلام از بهین یاب',
  productionOfwork: 'تولید حق العمل کاری',
  ownerOfBrand_License: 'صاحب برند / مجوز:',
  productioSummery: 'شرح تولید:',

  /***************************** صفحه چت  *********************/
  messagesInbox: 'صندوق پیام',
  message: 'پیام',

  restOfContent: 'ادامه مطلب',
  share: 'اشتراک گذاری',
  download: 'دانلود',
  closeContent: 'بستن',
  messageType: 'نوع پیام : ',
  messageStatus: 'وضعیت : ',
  privateMessages: 'شخصی',
  publicMessages: 'عمومی',
  seeMessage: 'مشاهده پیام',
  unseenMessage: '* خوانده نشده',
  haveNewMessage: 'پیغام جدیدی دارید',
  noMessageToShow: '" پیامی برای نمایش وجود ندارد "',
  readAllMessages: 'خواندن همه پیام ها',

  /************************ راهنمای تاجر  **********************/
  businessmanGuideS: 'راهنمای تاجر',
  announcements: 'اطلاعیه ها',
  announcementsType: 'نوع اطلاعیه : ',
  noAnnouncementToShow: '" اطلاعیه ای برای نمایش وجود ندارد "',

  News: 'اخبار و رویدادها',
  documents: 'مستندات',
  newsSource: 'لینک مرتبط با خبر',
  reciveGuideFile: 'دریافت فایل ',
  savedDocMessage: 'فایل راهنما در داخل پوشه NTWS ذخیره شد',

  accessTitle: 'مجوز دسترسی',
  accessMessage: 'برای دانلود فایل مجوز دسترسی به حافظه دستگاه نیاز است',
  accessDontGranted: 'مجوز دسترسی تایید نشد ...',
  fileSavedSuccessfully: 'فایل در پوشه "NTSW" با موفقیت ذخیره شد',
  downlodingFileText: 'در حال دریافت فایل  ',
  pleaseWait: 'لطفا منتظر بمانید ...',
  viewFile: 'مشاهده فایل',

  /************************ فروش با حواله   **********************/
  saleWithDraft: 'فروش با حواله',
  draftNum: 'شماره حواله :',
  buyerInfo: 'اطلاعات خریدار',
  code_natinalCode: 'کد/ شناسه ملی :',
  brandName: 'نام برند : ',
  ring_width: 'رینگ/فاق/پهنا : ',
  scanDraftBarcode: 'جهت استعلام حواله، بارکد را اسکن کنید',
  draftInputError: 'شماره حواله را وارد کنید',
  draftWarning:
    'حداکثر دو ماه پس از صدور حواله فرصت دارید تا نسبت به ثبت سند فروش در سامانه جامع تجارت اقدام نمایید. در صورت عدم ثبت فروش پس از این تاریخ، مجددا به همین تعداد برای شما حواله صادر می شود.',
  submitSale: 'ثبت فروش',
  saleDocumentInfo: 'اطلاعات سند فروش',
  saleDriftInfosError: 'تکمیل اطلاعات خریدار اجباری می باشد',
  enterPriceValue: 'درج مبلغ واحد حواله اجباری است',
  chassieNumberConfirmation:
    'در صورتیکه شماره شاسی درج شده در اصل سند ناوگان با شماره شاسی مذکور مطابقت دارد و مورد تایید شما میباشد، گزینه ثبت را انتخاب نمایید.',

  /************************ SellToMobileUser Screen  **********************/
  mobileRetail: 'خرده فروشی تلفن همراه',
  invoicing: 'صدور فاکتور',
  legalBuyer: 'خریدار حقوقی',
  realBuyer: 'خریدار حقیقی',
  nationalCode_ID: 'کد/شناسه ملی :',
  companyName: 'نام شرکت :',
  CEO_NationalCode: 'کد ملی مدیر عامل :',
  CompanyNationalID: 'شناسه ملی شرکت :',
  buyerNationalCode: 'کد ملی خریدار :',
  scanTrackingCodeBarcode: 'جهت استعلام شناسه رهگیری، بارکد را اسکن کنید',
  addStuff: 'افزودن کالا',
  invalidNationalID: 'شناسه ملی وارد شده معتبر نیست',
  trackingCodeInfos: 'اطلاعات شناسه رهگیری',
  otherServicesListEmptyMessage: "هنوز خدماتی اضافه نشده است\nبا انتخاب دکمه ' + ' خدمات جدید اضافه کنید",
  serviceDescription: 'شرح خدمات :',
  fillServiceDescription: 'شرح خدمات را وارد کنید',
  enterCompanynationalID: 'شناسه ۱۱ رقمی را وارد کنید',
  saleDocDate: 'تاریخ سند(فروش):',
  sametrackingCodeStuffError: 'این شناسه رهگیری قبلا به لیست کالا اضافه شده است',
  stuffsPiceValues: 'مجموع مبلغ کالاها :',
  servicesPiceValues: 'مجموع مبلغ سایر خدمات :',
  priceToBePayed: 'مجموع مبلغ قابل پرداخت',
  cancelSale: 'لغو فروش',
  finalSell: 'فروش نهایی',
  deleteChoosenService: 'خدمات انتخاب شده حذف شود؟',
  cancelSaleWarning: 'برای لغو فروش مطمئن هستید ؟',
  finalSellWarning: 'برای فروش نهایی مطمئن هستید؟',
  sellToMobileUserTooltip: 'در این بخش می توانید نسبت به ثبت خرده فروشی تلفن همراه اقدام نمایید.',
  houseStuffRetailTooltip: 'در این بخش می توانید نسبت به ثبت خرده فروشی لوازم خانگی اقدام نمایید.',
  factorcreatedSuccessfully: 'اطلاعات فاکتور به مصرف کننده پیامک شد. در صورت قطعی شدن فروش بر روی دکمه فروش نهایی کلیک کنید',
  finalSubmitSeccessfully: 'ثبت نهایی فاکتور فروش با موفقیت انجام شد',
  CancelDocSeccessfully: 'لغو فاکتور فروش با موفقیت انجام شد',
  finalSaleCode: 'کد فروش نهایی',
  factorSmsSendedToBuyer: 'اطلاعات فاکتور به همراه کد فروش نهایی به خریدار پیامک شد.',

  /************************ ElectronicInvoice Screen  **********************/
  ElectronicInvoice: 'فاکتور الکترونیکی فروش',
  invoiceDate: 'تاریخ صورتحساب :',
  invoiceSummery: 'شرح فاکتور :',
  backFromSell: 'برگشت از فروش',
  Unit: 'واحد شمارش : ',
  currencieType: 'نوع ارز :',
  currencyExchangeRate: 'نرخ برابری ارز(ریال):',
  amountOfDiscount: 'مبلغ تخفیف : ',
  vat: 'مالیات بر ارزش افزوده :',
  valueAddedEffects: 'عوارض بر ارزش افزوده :',
  otherEffects: 'سایر عوارض :',
  firstName: 'نام :',
  lastname: 'نام خانوادگی :',
  buyerAdress: 'آدرس خریدار :',
  stuffCodeErrorText: 'شناسه کالا را وارد کنید',
  countingUnitErrorText: 'واحد شمارش را وارد کنید',
  unitPriceErrorText: 'مبلغ واحد را وارد کنید',
  stuffGroupIdErrorText: 'گروه کالا را انتخاب کنید',
  stuffCategoryIdErrorText: 'طبقه کالا را انتخاب کنید',
  finlaPrice: 'مبلغ نهایی :',
  state: 'استان : ',
  city: 'شهر : ',
  noStuffForSelectedGroupAndCategeroy: 'برای گروه و طبقه کالا انتخاب شده، کالایی وجود ندارد',
  electronicInvoiceTooltip: 'در این بخش می توانید اسناد فاکتور الکترونیکی فروش را ثبت نمایید.',

  /************************ HomeApplianceRetail Screen  **********************/
  homeApplianceRetailTitle: 'خرده فروشی لوازم خانگی',
  /***********************************************************************/

  update: 'بروز رسانی',
  appVersionIsLatestVersion: 'نسخه اپلیکیشن بروز می باشد',
  updateReadStoragePermissionQuestion: 'برای نصب نسخه جدید، دسترسی به حافظه نیاز است',
  updateAvailableUnnecessary:
    'نسخه جدیدی از برنامه موجود است.\nپیشنهاد می شود که با انتخاب گزینه `بروزرسانی`، از نسخه جدید استفاده نمایید',
  updateAvailableNecessary: 'این نسخه از برنامه پشتیبانی نمی شود.\nلطفا برای ادامه استفاده از برنامه، آن را بروزرسانی نمایید',

  appLoadingError: 'خطا در بارگذاری برنامه',
  webServiceConnectionError:
    'ارتباط با سرور برقرار نیست.\nلطفا اینترنت گوشی خود را چک کرده و در صورت برقراری اینترنت چند دقیقه دیگر مجددا تلاش نمایید',
  webServiceError: 'خطایی رخ داده است.\nلطفا چند دقیقه دیگر مجددا تلاش نمایید',
  loggedOutError: 'حساب شما از سامانه خارج شده است\nلطفا دوباره وارد شوید',
  anErrorOccurred: 'خطایی رخ داده است!',
  userCancelledError: 'کاربر انصراف داده است',

  connectionErrorAndTip:
    'خطایی در ارتباط رخ داده است\nلطفا اینترنت گوشی خود را چک کنید و درصورت استفاده از پروکسی، آن را قطع نمایید',
}

export default strings

// Successfully
